# Generated by Django 5.2.7 on 2025-12-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
