# Generated by Django 5.2.7 on 2025-11-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0002_user_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
