# Generated by Django 5.2.7 on 2025-11-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0003_remove_book_author_remove_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
    ]
