# Generated by Django 5.2.7 on 2025-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0005_book_author_book_category_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.TextField(blank=True, null=True, verbose_name='Status'),
        ),
    ]
