# Generated by Django 5.2.7 on 2025-12-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0006_book_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='name',
        ),
    ]
