# Generated by Django 5.2.7 on 2025-12-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0007_rename_full_name_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='saybabook_app.author'),
        ),
    ]
