# Generated by Django 5.2.7 on 2025-12-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0008_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='book_category',
        ),
    ]
