# Generated by Django 5.2.7 on 2025-12-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0009_rename_category_book_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userProfile', to='saybabook_app.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='User Profile'),
        ),
    ]
