# Generated by Django 5.2.7 on 2025-12-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0010_user_user_profile_id_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userProfile', to='saybabook_app.userprofile'),
        ),
    ]
