# Generated by Django 5.2.7 on 2025-12-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0011_alter_user_user_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
