# Generated by Django 5.2.7 on 2025-12-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0012_rename_user_profile_id_user_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
    ]
