# Generated by Django 5.2.7 on 2025-12-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0015_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
