# Generated by Django 5.2.7 on 2025-12-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saybabook_app', '0017_userprofile_user_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_user', to='saybabook_app.userprofile'),
        ),
    ]
